Created recipe editing functionality
redhat-beyond/tasties pull request #105
Opened 2023-01-17 18:12 UTC by efraimvis

Added functionality to edit recipes, based off of [my recipe creation PR](https://github.com/redhat-beyond/tasties/pull/100).

- No tests yet.
- A user may only edit a recipe that they had created

Recipe before editing:
![localhost_8000_view_recipe_74_](https://user-images.githubusercontent.com/116169213/212978199-bb8fae9b-b8ee-4bcc-aded-dd17e1f35524.png)

Recipe being edited:
![localhost_8000_edit_recipe_74_](https://user-images.githubusercontent.com/116169213/212978254-c135ea77-8e89-4326-a2eb-7f75ddbb9ff6.png)

Recipe after edit:
![localhost_8000_view_recipe_74_ (2)](https://user-images.githubusercontent.com/116169213/212978287-d9c1f48a-32e3-44cc-b16a-f2d4bcd4f1ab.png)

2023-01-17 18:52 UTC, svatares commented
Hi @efraimvis please resolve conflicts

2023-01-17 19:54 UTC, efraimvis commented
> Hi @efraimvis please resolve conflicts

Done.

2023-01-18 17:19 UTC, GalOved requested changes
Good work, It all looking good for me please add one extra line in the file and I will approve this PR.

2023-01-18 17:19 UTC, GalOved commented on tasties_app/templates/tasties_app/create_recipe.html
> +{% endblock %}
Please add in the end of the file 1 extrea line

2023-01-18 17:19 UTC, GalOved commented on tasties_app/templates/tasties_app/edit_recipe.html
> +{% block crud-action %}<h1>Edit Recipe</h1>{% endblock %}
Please add in the end of the file 1 extrea line.

2023-01-18 20:40 UTC, GalOved submitted a review, later dismissed
LGTM

2023-01-18 20:53 UTC, svatares commented
Squash commit please

2023-01-19 10:30 UTC, efraimvis commented
Introduced a new, functioning, "Edit Recipe" button to allow users to edit their recipes from their `view_recipe` page.
![image](https://user-images.githubusercontent.com/116169213/213418952-2ed80374-ae6c-42f6-acef-79f76005e458.png)

2023-01-19 11:17 UTC, GilShechter commented
I think it would be nicer if the edit button will be placed above the date.

2023-01-19 11:31 UTC, GalOved approved these changes

2023-01-19 13:20 UTC, GilShechter commented
As I've been told before by our mentors, good tests don't need to be explained by comments.
Rather than that, everything looks good.

2023-01-19 15:07 UTC, GalOved submitted a review, later dismissed
LGTM

2023-01-19 15:18 UTC, natifridman commented
> As I've been told before by our mentors, good tests don't need to be explained by comments. Rather than that, everything looks good.

+1

2023-01-19 15:34 UTC, efraimvis commented
> > As I've been told before by our mentors, good tests don't need to be explained by comments. Rather than that, everything looks good.
> 
> +1

Does that mean I should remove the comments from the tests?

2023-01-19 15:37 UTC, natifridman commented
> Does that mean I should remove the comments from the tests?

I think so, your code should be clear enough to understand without comments

2023-01-19 15:42 UTC, efraimvis commented
> > Does that mean I should remove the comments from the tests?
> 
> I think so, your code should be clear enough to understand without comments

I see. The test are quite minimal, so It's quite clear what everything does. I removed the comments.

2023-01-19 16:21 UTC, natifridman approved these changes

2023-01-19 16:23 UTC, GalOved approved these changes

2023-01-19 17:00 UTC, efraimvis commented
I see there's been an approval. I'm squashing commits 👍

2023-01-19 17:11 UTC, efraimvis commented
@natifridman @liornoy Squashed commits.

2023-01-19 17:21 UTC, GalOved approved these changes

2023-01-19 18:36 UTC, natifridman approved these changes

2023-01-19 18:36 UTC, merged