Adding webpage and initialize settings
redhat-beyond/tasties pull request #21
Opened 2022-11-10 20:06 UTC by ohadrevach

Creating web page application using the django,
set up it's requirements and add index.html

2022-11-10 20:08 UTC, GilShechter submitted a review, later dismissed
Looks good to me

2022-11-10 20:11 UTC, efraimvis approved these changes
Looks good.

2022-11-10 20:13 UTC, efraimvis requested changes
Please link this PR to issue #15

2022-11-10 20:15 UTC, efraimvis submitted a review, later dismissed

2022-11-10 20:17 UTC, GalOved reviewed
In index.html i add a review.

2022-11-13 07:45 UTC, WaseemAbuSobe approved these changes

2022-11-13 07:45 UTC, WaseemAbuSobe commented
looking good

2022-11-13 07:47 UTC, WaseemAbuSobe approved these changes
looking good

2022-11-13 13:06 UTC, liornoy commented
@ohadrevach did you see Gal's review?

2022-11-13 15:59 UTC, natifridman reviewed
I guess `webpage` is a temporary name?

2022-11-13 16:04 UTC, GilShechter commented
> I guess `webpage` is a temporary name?

Well, we named the project "tasties" so we have a directory with this name.
Then we created the application for the web page, so, what should we call it? 
The project name is already taken.

2022-11-13 16:13 UTC, natifridman commented
> > I guess `webpage` is a temporary name?
> 
> Well, we named the project "tasties" so we have a directory with this name. Then we created the application for the web page, so, what should we call it? The project name is already taken.

Let's keep it with this name for now, but think about it when you will work on the models

2022-11-13 16:38 UTC, ohadrevach commented on webpage/templates/webpage/index.html
> +</html>
Fixed

2022-11-14 09:01 UTC, natifridman submitted a review, later dismissed
Please squash the commits so we can merge it

2022-11-15 18:09 UTC, WaseemAbuSobe submitted a review, later dismissed

2022-11-16 12:30 UTC, efraimvis approved these changes
I can see you squashed the commits together, I don't see any probelms.

2022-11-16 12:33 UTC, GalOved approved these changes
All looking good to me.

2022-11-16 14:00 UTC, svatares approved these changes

2022-11-16 14:00 UTC, merged