Adding recipe model to tasties.
redhat-beyond/tasties pull request #48
Opened 2022-11-30 13:27 UTC by GalOved

Adding recipe model to tasties app.
Add a delete and edit methods to the recipe model. 
Adding a test for the recipe model and for the methods.

2022-11-30 14:25 UTC, efraimvis requested changes
I think we might need to have the 0001_initial migration merged (or included in the PR) for the tests to pass.

2022-11-30 15:19 UTC, WaseemAbuSobe approved these changes

2022-12-05 17:59 UTC, WaseemAbuSobe approved these changes

2022-12-05 18:00 UTC, WaseemAbuSobe commented
check you'r PyTest.

2022-12-05 18:34 UTC, closed without merging