Adding a feature for categories
redhat-beyond/tasties pull request #71
Opened 2023-01-02 21:16 UTC by GalOved

Adding a feature of showing all the categories are found in the database and showing tham on the html file.

2023-01-02 23:44 UTC, GilShechter commented on tasties_app/templates/tasties_app/base.html
> +    {% block content %}
Please give the block a different name, because there is already a block named `content` and it is used by other templates that inherit this one.

2023-01-02 23:46 UTC, GilShechter commented on tasties_app/templates/tasties_app/base.html
> +                <li style="display:inline">
Style should be in the CSS file, as I've been told in my PR.

2023-01-02 23:47 UTC, GilShechter commented on tasties_app/views.py
> +    objects = Category.objects.all()
Please give this variable a meaningful name (like `category_list` for example).

2023-01-02 23:49 UTC, GilShechter requested changes
We don't want guests to see the category menu, so please put it under an if condition:
`{% if user.is_authenticated %}`

You can see an example in line 45.

2023-01-03 08:28 UTC, GilShechter commented on tasties_app/views.py
> +    return render(request, 'tasties_app/base.html', {'objects': categories_list})
Please change the name of the objects as well.
You will also need to change it in the HTML file.

2023-01-03 13:29 UTC, GilShechter approved these changes
LGTM.

2023-01-03 18:24 UTC, efraimvis approved these changes

2023-01-03 19:16 UTC, natifridman reviewed
Looks good. Are these going to be your final categories? I wonder if you'll add more categories, wouldn't it be a big list that will fill the page?

2023-01-04 11:33 UTC, efraimvis requested changes
After some thinking, I've come to the conclusion that the functionality of this PR (showing categories on the navbar) should be added to `recipes.html` rather than `base.html`. This is because we want to see the categories when we browse the recipes - a topbar full of categories is quite out of place when viewing a particular recipe, for example.

2023-01-04 12:33 UTC, closed without merging